/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as ChatgptRouteImport } from './routes/chatgpt'
import { Route as EmailTemplateRouteImport } from './routes/email-template'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as MentionsLegalesChatgptRouteImport } from './routes/mentions-legales-chatgpt'
import { Route as NvidiaRouteImport } from './routes/nvidia'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PolitiqueConfidentialiteChatgptRouteImport } from './routes/politique-confidentialite-chatgpt'
import { Route as ApiPublicAdminRouteImport } from './routes/api/public/admin'
import { Route as ApiPublicLeadFormRouteImport } from './routes/api/public/lead-form'
import { Route as ApiPublicLeadsRouteImport } from './routes/api/public/leads'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatgptRoute = ChatgptRouteImport.update({
  id: '/chatgpt',
  path: '/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailTemplateRoute = EmailTemplateRouteImport.update({
  id: '/email-template',
  path: '/email-template',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesChatgptRoute = MentionsLegalesChatgptRouteImport.update({
  id: '/mentions-legales-chatgpt',
  path: '/mentions-legales-chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const NvidiaRoute = NvidiaRouteImport.update({
  id: '/nvidia',
  path: '/nvidia',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PolitiqueConfidentialiteChatgptRoute =
  PolitiqueConfidentialiteChatgptRouteImport.update({
    id: '/politique-confidentialite-chatgpt',
    path: '/politique-confidentialite-chatgpt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminRoute = ApiPublicAdminRouteImport.update({
  id: '/api/public/admin',
  path: '/api/public/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadFormRoute = ApiPublicLeadFormRouteImport.update({
  id: '/api/public/lead-form',
  path: '/api/public/lead-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsRoute = ApiPublicLeadsRouteImport.update({
  id: '/api/public/leads',
  path: '/api/public/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/chatgpt': typeof ChatgptRoute
  '/email-template': typeof EmailTemplateRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentions-legales-chatgpt': typeof MentionsLegalesChatgptRoute
  '/nvidia': typeof NvidiaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-confidentialite-chatgpt': typeof PolitiqueConfidentialiteChatgptRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/chatgpt': typeof ChatgptRoute
  '/email-template': typeof EmailTemplateRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentions-legales-chatgpt': typeof MentionsLegalesChatgptRoute
  '/nvidia': typeof NvidiaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-confidentialite-chatgpt': typeof PolitiqueConfidentialiteChatgptRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/chatgpt': typeof ChatgptRoute
  '/email-template': typeof EmailTemplateRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/mentions-legales-chatgpt': typeof MentionsLegalesChatgptRoute
  '/nvidia': typeof NvidiaRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/politique-confidentialite-chatgpt': typeof PolitiqueConfidentialiteChatgptRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/lead-form': typeof ApiPublicLeadFormRoute
  '/api/public/leads': typeof ApiPublicLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/chatgpt'
    | '/email-template'
    | '/mentions-legales'
    | '/mentions-legales-chatgpt'
    | '/nvidia'
    | '/politique-confidentialite'
    | '/politique-confidentialite-chatgpt'
    | '/api/public/admin'
    | '/api/public/lead-form'
    | '/api/public/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/chatgpt'
    | '/email-template'
    | '/mentions-legales'
    | '/mentions-legales-chatgpt'
    | '/nvidia'
    | '/politique-confidentialite'
    | '/politique-confidentialite-chatgpt'
    | '/api/public/admin'
    | '/api/public/lead-form'
    | '/api/public/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-docs'
    | '/chatgpt'
    | '/email-template'
    | '/mentions-legales'
    | '/mentions-legales-chatgpt'
    | '/nvidia'
    | '/politique-confidentialite'
    | '/politique-confidentialite-chatgpt'
    | '/api/public/admin'
    | '/api/public/lead-form'
    | '/api/public/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiDocsRoute: typeof ApiDocsRoute
  ChatgptRoute: typeof ChatgptRoute
  EmailTemplateRoute: typeof EmailTemplateRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  MentionsLegalesChatgptRoute: typeof MentionsLegalesChatgptRoute
  NvidiaRoute: typeof NvidiaRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PolitiqueConfidentialiteChatgptRoute: typeof PolitiqueConfidentialiteChatgptRoute
  ApiPublicAdminRoute: typeof ApiPublicAdminRoute
  ApiPublicLeadFormRoute: typeof ApiPublicLeadFormRoute
  ApiPublicLeadsRoute: typeof ApiPublicLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatgpt': {
      id: '/chatgpt'
      path: '/chatgpt'
      fullPath: '/chatgpt'
      preLoaderRoute: typeof ChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-template': {
      id: '/email-template'
      path: '/email-template'
      fullPath: '/email-template'
      preLoaderRoute: typeof EmailTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales-chatgpt': {
      id: '/mentions-legales-chatgpt'
      path: '/mentions-legales-chatgpt'
      fullPath: '/mentions-legales-chatgpt'
      preLoaderRoute: typeof MentionsLegalesChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nvidia': {
      id: '/nvidia'
      path: '/nvidia'
      fullPath: '/nvidia'
      preLoaderRoute: typeof NvidiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite-chatgpt': {
      id: '/politique-confidentialite-chatgpt'
      path: '/politique-confidentialite-chatgpt'
      fullPath: '/politique-confidentialite-chatgpt'
      preLoaderRoute: typeof PolitiqueConfidentialiteChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin': {
      id: '/api/public/admin'
      path: '/api/public/admin'
      fullPath: '/api/public/admin'
      preLoaderRoute: typeof ApiPublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-form': {
      id: '/api/public/lead-form'
      path: '/api/public/lead-form'
      fullPath: '/api/public/lead-form'
      preLoaderRoute: typeof ApiPublicLeadFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads': {
      id: '/api/public/leads'
      path: '/api/public/leads'
      fullPath: '/api/public/leads'
      preLoaderRoute: typeof ApiPublicLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiDocsRoute: ApiDocsRoute,
  ChatgptRoute: ChatgptRoute,
  EmailTemplateRoute: EmailTemplateRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  MentionsLegalesChatgptRoute: MentionsLegalesChatgptRoute,
  NvidiaRoute: NvidiaRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PolitiqueConfidentialiteChatgptRoute: PolitiqueConfidentialiteChatgptRoute,
  ApiPublicAdminRoute: ApiPublicAdminRoute,
  ApiPublicLeadFormRoute: ApiPublicLeadFormRoute,
  ApiPublicLeadsRoute: ApiPublicLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
